### ISSUE TITLE
关于背部法线训练

### ISSUE THREAD

**Issue by hungsing92** [lingtengqiu/Open-PIFuhd#6]
你好，
    我在训练背部法线的时候出现如下情况
![image](https://user-images.githubusercontent.com/27841572/132461779-65021050-9075-4c93-a570-ac10252bae4c.png)
   请问你有没有遇到或者有没有什么头绪？
   非常感谢！

**Comment by lingtengqiu** [comment]
按照paper 里头的内容，没有使用GAN LOSS，你可以加gan loss试一试，虽然出现细节，但是有很多artifacts。
而且按道理来说就是很难估计背部的信息。你这个是训练多少个epoch的，推荐是10个epoch 左右的model。
你可以kan loss 会有你期望的细节，但是有的会出现比较大的artifacts。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lingtengqiu/Open-PIFuhd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月8日(星期三) 下午3:01
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lingtengqiu/Open-PIFuhd] 关于背部法相训练 (#6)





 
你好，
 我在训练背部法线的时候出现如下情况
 
 请问你有没有遇到或者有没有什么头绪？
 非常感谢！
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hungsing92** [comment]
我这个应该是训练epoch较少导致的。看了下你训练过程中的图片，也是会有这种瑕疵，看来需要更多epoch数才会缓解。
非常感谢！
